# This is a basic workflow to help you get started with Actions

name: Deploy recipebook.functions

on:
  workflow_run:
    workflows: ["CI Build"]
    branches: [master]
    types: 
      - completed

jobs:

  deploy:
    runs-on: windows-latest
    
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2
      with:
        name: recipebook-functions
        path: to-deploy
    
    - name: 'Service Principal Login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: 'Deploy Azure Function'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: recipebook-functions
        package: to-deploy

    - name: logout
      run: |
        az logout
