# This is a basic workflow to help you get started with Actions

name: Deploy recipebook.functions

on:
  workflow_run:
    workflows: ["CI Build"]
    branches: [master]
    types: 
      - completed

jobs:

  deploy:
    runs-on: windows-latest
    
    steps:
    - name: 'Service Principal Login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: logout
      run: |
        az logout
